/**
 * MT4/MT5 MQL Code Exporter
 * 
 * Generates MetaTrader Expert Advisor code from strategy parameters.
 */

import { StrategyParams } from './types';

export interface MQLExportConfig {
    strategyName: string;
    params: StrategyParams;
    symbol: string;
    timeframe: string;
    magicNumber: number;
    lotSize: number;
    useAutolot: boolean;
    riskPercent: number;
}

export const DEFAULT_MQL_CONFIG: MQLExportConfig = {
    strategyName: 'Exported Strategy',
    params: {},
    symbol: 'XAUUSD',
    timeframe: 'PERIOD_M30',
    magicNumber: 123456,
    lotSize: 0.1,
    useAutolot: true,
    riskPercent: 2
};

/**
 * Generate MQL4 Expert Advisor code
 */
export function generateMQL4(config: MQLExportConfig): string {
    const { strategyName, params, symbol, timeframe, magicNumber, lotSize, useAutolot, riskPercent } = config;

    // Convert params to MQL input variables
    const inputVariables = Object.entries(params)
        .filter(([_, v]) => typeof v === 'number' || typeof v === 'boolean')
        .map(([key, value]) => {
            const type = typeof value === 'boolean' ? 'bool' : 'double';
            const val = typeof value === 'boolean' ? (value ? 'true' : 'false') : value;
            return `input ${type} ${key} = ${val};`;
        })
        .join('\n');

    return `//+------------------------------------------------------------------+
//|                                        ${strategyName}.mq4 |
//|                         Generated by Delcea's Platform           |
//|                              https://delcea.platform             |
//+------------------------------------------------------------------+
#property copyright "Delcea's Backtesting Platform"
#property link      "https://delcea.platform"
#property version   "1.00"
#property strict

//--- Input Parameters
input int MagicNumber = ${magicNumber};
input double LotSize = ${lotSize};
input bool UseAutoLot = ${useAutolot};
input double RiskPercent = ${riskPercent};
${inputVariables}

//--- Global Variables
int TradesOpened = 0;
double AccountStartBalance;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
{
    AccountStartBalance = AccountBalance();
    Print("${strategyName} EA initialized on ${symbol}");
    Print("Magic Number: ", MagicNumber);
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("${strategyName} EA removed. Total trades: ", TradesOpened);
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk                                  |
//+------------------------------------------------------------------+
double CalculateLotSize(double stopLossPips)
{
    if(!UseAutoLot) return LotSize;
    
    double tickValue = MarketInfo(Symbol(), MODE_TICKVALUE);
    double riskAmount = AccountBalance() * (RiskPercent / 100.0);
    double lotSize = riskAmount / (stopLossPips * tickValue);
    
    double minLot = MarketInfo(Symbol(), MODE_MINLOT);
    double maxLot = MarketInfo(Symbol(), MODE_MAXLOT);
    double lotStep = MarketInfo(Symbol(), MODE_LOTSTEP);
    
    lotSize = MathFloor(lotSize / lotStep) * lotStep;
    lotSize = MathMax(minLot, MathMin(maxLot, lotSize));
    
    return lotSize;
}

//+------------------------------------------------------------------+
//| Check for open positions                                          |
//+------------------------------------------------------------------+
bool HasOpenPosition()
{
    for(int i = OrdersTotal() - 1; i >= 0; i--)
    {
        if(OrderSelect(i, SELECT_BY_POS))
        {
            if(OrderSymbol() == Symbol() && OrderMagicNumber() == MagicNumber)
            {
                return true;
            }
        }
    }
    return false;
}

//+------------------------------------------------------------------+
//| Get signal (implement your strategy logic here)                   |
//+------------------------------------------------------------------+
int GetSignal()
{
    // TODO: Implement your strategy signal logic
    // Return: 1 for BUY, -1 for SELL, 0 for no signal
    
    // Example: Simple MA crossover
    // double fastMA = iMA(Symbol(), ${timeframe}, 10, 0, MODE_SMA, PRICE_CLOSE, 0);
    // double slowMA = iMA(Symbol(), ${timeframe}, 30, 0, MODE_SMA, PRICE_CLOSE, 0);
    // double fastMAPrev = iMA(Symbol(), ${timeframe}, 10, 0, MODE_SMA, PRICE_CLOSE, 1);
    // double slowMAPrev = iMA(Symbol(), ${timeframe}, 30, 0, MODE_SMA, PRICE_CLOSE, 1);
    
    // if(fastMAPrev <= slowMAPrev && fastMA > slowMA) return 1;  // Buy
    // if(fastMAPrev >= slowMAPrev && fastMA < slowMA) return -1; // Sell
    
    return 0;
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
    // Only trade on new bar
    static datetime lastBar = 0;
    if(Time[0] == lastBar) return;
    lastBar = Time[0];
    
    // Check for existing positions
    if(HasOpenPosition()) return;
    
    // Get signal
    int signal = GetSignal();
    
    if(signal == 0) return;
    
    // Calculate SL/TP
    double atr = iATR(Symbol(), ${timeframe}, 14, 0);
    double slPips = atr * 2;
    double tpPips = slPips * 2;
    
    double lots = CalculateLotSize(slPips / Point);
    
    if(signal == 1) // BUY
    {
        double sl = Ask - slPips;
        double tp = Ask + tpPips;
        
        int ticket = OrderSend(Symbol(), OP_BUY, lots, Ask, 3, sl, tp, 
                               "${strategyName}", MagicNumber, 0, clrGreen);
        
        if(ticket > 0)
        {
            TradesOpened++;
            Print("BUY order opened. Ticket: ", ticket);
        }
        else
        {
            Print("Error opening BUY order: ", GetLastError());
        }
    }
    else if(signal == -1) // SELL
    {
        double sl = Bid + slPips;
        double tp = Bid - tpPips;
        
        int ticket = OrderSend(Symbol(), OP_SELL, lots, Bid, 3, sl, tp,
                               "${strategyName}", MagicNumber, 0, clrRed);
        
        if(ticket > 0)
        {
            TradesOpened++;
            Print("SELL order opened. Ticket: ", ticket);
        }
        else
        {
            Print("Error opening SELL order: ", GetLastError());
        }
    }
}

//+------------------------------------------------------------------+
`;
}

/**
 * Generate MQL5 Expert Advisor code
 */
export function generateMQL5(config: MQLExportConfig): string {
    const { strategyName, params, magicNumber, lotSize, useAutolot, riskPercent } = config;

    const inputVariables = Object.entries(params)
        .filter(([_, v]) => typeof v === 'number' || typeof v === 'boolean')
        .map(([key, value]) => {
            const type = typeof value === 'boolean' ? 'bool' : 'double';
            const val = typeof value === 'boolean' ? (value ? 'true' : 'false') : value;
            return `input ${type} ${key} = ${val};`;
        })
        .join('\n');

    return `//+------------------------------------------------------------------+
//|                                        ${strategyName}.mq5 |
//|                         Generated by Delcea's Platform           |
//|                              https://delcea.platform             |
//+------------------------------------------------------------------+
#property copyright "Delcea's Backtesting Platform"
#property link      "https://delcea.platform"
#property version   "1.00"

#include <Trade\\Trade.mqh>

//--- Input Parameters
input ulong MagicNumber = ${magicNumber};
input double LotSize = ${lotSize};
input bool UseAutoLot = ${useAutolot};
input double RiskPercent = ${riskPercent};
${inputVariables}

//--- Global Objects
CTrade trade;
int TradesOpened = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
{
    trade.SetExpertMagicNumber(MagicNumber);
    trade.SetDeviationInPoints(10);
    trade.SetTypeFilling(ORDER_FILLING_IOC);
    
    Print("${strategyName} EA initialized");
    return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{
    Print("${strategyName} EA removed. Total trades: ", TradesOpened);
}

//+------------------------------------------------------------------+
//| Calculate lot size based on risk                                  |
//+------------------------------------------------------------------+
double CalculateLotSize(double stopLossPips)
{
    if(!UseAutoLot) return LotSize;
    
    double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
    double riskAmount = AccountInfoDouble(ACCOUNT_BALANCE) * (RiskPercent / 100.0);
    double lots = riskAmount / (stopLossPips * tickValue);
    
    double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
    double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
    double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
    
    lots = MathFloor(lots / lotStep) * lotStep;
    lots = MathMax(minLot, MathMin(maxLot, lots));
    
    return lots;
}

//+------------------------------------------------------------------+
//| Check for open positions                                          |
//+------------------------------------------------------------------+
bool HasOpenPosition()
{
    for(int i = PositionsTotal() - 1; i >= 0; i--)
    {
        if(PositionSelectByTicket(PositionGetTicket(i)))
        {
            if(PositionGetString(POSITION_SYMBOL) == _Symbol && 
               PositionGetInteger(POSITION_MAGIC) == MagicNumber)
            {
                return true;
            }
        }
    }
    return false;
}

//+------------------------------------------------------------------+
//| Get signal (implement your strategy logic here)                   |
//+------------------------------------------------------------------+
int GetSignal()
{
    // TODO: Implement your strategy signal logic
    // Return: 1 for BUY, -1 for SELL, 0 for no signal
    
    return 0;
}

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
{
    // Only trade on new bar
    static datetime lastBar = 0;
    datetime currentBar = iTime(_Symbol, PERIOD_M30, 0);
    if(currentBar == lastBar) return;
    lastBar = currentBar;
    
    // Check for existing positions
    if(HasOpenPosition()) return;
    
    // Get signal
    int signal = GetSignal();
    
    if(signal == 0) return;
    
    // Calculate SL/TP
    int atrHandle = iATR(_Symbol, PERIOD_M30, 14);
    double atrBuffer[];
    ArraySetAsSeries(atrBuffer, true);
    CopyBuffer(atrHandle, 0, 0, 1, atrBuffer);
    double atr = atrBuffer[0];
    
    double slPips = atr * 2;
    double tpPips = slPips * 2;
    
    double lots = CalculateLotSize(slPips / _Point);
    double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
    double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
    
    if(signal == 1) // BUY
    {
        double sl = ask - slPips;
        double tp = ask + tpPips;
        
        if(trade.Buy(lots, _Symbol, ask, sl, tp, "${strategyName}"))
        {
            TradesOpened++;
            Print("BUY order opened");
        }
    }
    else if(signal == -1) // SELL
    {
        double sl = bid + slPips;
        double tp = bid - tpPips;
        
        if(trade.Sell(lots, _Symbol, bid, sl, tp, "${strategyName}"))
        {
            TradesOpened++;
            Print("SELL order opened");
        }
    }
    
    IndicatorRelease(atrHandle);
}

//+------------------------------------------------------------------+
`;
}

/**
 * Download MQL file
 */
export function downloadMQLFile(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}
